# application.properties    
# Author: Edoardo Sabatini
# Date 2026-05-20
# Description: This file contains the configuration properties for the Spring Boot application. 
# It sets the application name and configures the API versioning strategy to use HTTP headers, 
# specifically the "X-API-Version" header, for determining the API version in incoming requests.

spring.application.name=backend
# Configures Spring 7 native API versioning strategy using HTTP Headers
spring.mvc.apiversion.use.header=X-API-Version
